apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ruby-app
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  type: ClusterIP

